### ISSUE TITLE
goTrough error

### ISSUE THREAD

**Issue by Greensky-gs** [RichardDorian/enigma-machine#1]
Hello, I use your package, and there's something that doesn't work. I don't know if this is an error from me or an issue in the source code, so I post it here.

Here is the error :
```
currentLetter = this.plugboard.goThrough(currentLetter);
                                       ^

TypeError: this.plugboard.goThrough is not a function
    at Enigma.calculateLetter (C:\Users\David\Documents\scripts\js\enigma-machine\node_modules\enigma-machine\build\Classes\Enigma.js:18:40)
    at Enigma.calculateString (C:\Users\David\Documents\scripts\js\enigma-machine\node_modules\enigma-machine\build\Classes\Enigma.js:40:36)
    at Object.<anonymous> (C:\Users\David\Documents\scripts\js\enigma-machine\index.js:7:21)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

And here is the code :
```js
const Enigma = require('enigma-machine')

const config = Enigma.generateEnigmaConfiguration()
console.log(config)
const machine = new Enigma.Enigma(config.rotors, config.reflector, config.plugboard)

console.log(machine.calculateString("Hello"))
```

I hope you'll find the problem. I'll maybe investigate on the error and make a pull request, but I'm not sure

**Comment by Greensky-gs** [comment]
Edit : I'm stupid. I didn't use the package correctly, the correct way to do this is like so :

```js
const Enigma = require('enigma-machine')

const config = Enigma.generateEnigmaConfiguration()
const machine = Enigma.Enigma.generateFromEnigmaConfig(config)
```
